FROM eclipse-temurin:21-jre

WORKDIR /app

ARG JAR_FILE

COPY ${JAR_FILE} app.jar

ENV SERVER_PORT=8080
ENV SPRING_PROFILES_ACTIVE=dev
ENV NACOS_SERVER_ADDR=192.168.199.107:8848
ENV JAVA_OPTS=""

EXPOSE ${SERVER_PORT}

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]